-- 메인 RDS(main datasource) 스키마 전체 생성.
--
-- 기존에는 이 스키마를 JPA(hibernate ddl-auto=update)가 애플리케이션 기동 시점에
-- 엔티티로부터 자동 생성했고, Flyway는 데이터 INSERT/스키마 보정만 담당했다.
-- 문제는 Spring Boot 기동 순서상 Flyway가 Hibernate보다 먼저(혹은 더 이르게) 실행될
-- 수 있어서, 테이블이 하나도 없는 새 환경(다른 컴퓨터/새 DB)에서 clone 후 최초 실행하면
-- V1 이하 마이그레이션이 "테이블이 아직 없다"며 실패하거나(예: 과거 V12) 조용히
-- no-op(IF EXISTS 가드)로 넘어가 버려서 정작 스키마가 전혀 만들어지지 않았다.
--
-- 이 마이그레이션은 그 근본 원인을 없애기 위해, 엔티티가 정의하는 테이블 구조를
-- Flyway 코드로 명시한다. 이후 ddl-auto는 validate로 바꿔서 Hibernate는 스키마를
-- "만들지" 않고 엔티티와 일치하는지 검증만 하도록 한다.
--
-- 여기서 만드는 스키마는 "V1이 실행되기 직전 시점"의 형태다. V3/V5/V6/V8/V9/V10/V11/
-- V12/V13/V15/V16이 그 뒤에서 원래 의도대로 컬럼 추가/제약조건 추가/타입 변경을
-- 순서대로 적용해서 최종적으로 지금의 엔티티와 같은 모습이 된다. (즉 여기서 그 뒤
-- 마이그레이션이 추가하는 컬럼/제약조건을 미리 넣지 않는다 - 특히 V12처럼 IF NOT EXISTS
-- 가드가 없는 ADD COLUMN이 있으면 중복 생성으로 실패하기 때문.)

-- =========================================================
-- 사용자 / 인증
-- =========================================================

CREATE TABLE users (
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL,
    password            VARCHAR(255),
    name                VARCHAR(255) NOT NULL,
    role                VARCHAR(20)  NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    verification_token  VARCHAR(255),
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    token_value      VARCHAR(1000) NOT NULL,
    expires_at       TIMESTAMPTZ NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_refresh_tokens_user_id UNIQUE (user_id),
    CONSTRAINT uk_refresh_tokens_token_value UNIQUE (token_value)
);

CREATE TABLE oauth_accounts (
    oauth_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    provider         VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL
);

-- =========================================================
-- 체크리스트 기준정보 (상품 / 주택유형 / 서류)
-- =========================================================

CREATE TABLE products (
    product_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(30)  NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_products_product_code UNIQUE (product_code)
);

CREATE TABLE housing_types (
    housing_type_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    housing_type_code VARCHAR(30)  NOT NULL,
    housing_type_name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_housing_types_code UNIQUE (housing_type_code)
);

CREATE TABLE checklist_sections (
    section_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_code VARCHAR(30)  NOT NULL,
    section_name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_checklist_sections_code UNIQUE (section_code)
);

CREATE TABLE checklist_groups (
    group_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    group_name VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT uk_checklist_groups_section_order UNIQUE (section_id, sort_order)
);

CREATE TABLE checklist_items (
    item_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id       BIGINT NOT NULL,
    group_id         BIGINT,
    item_name        VARCHAR(200) NOT NULL,
    sort_order       INTEGER NOT NULL,
    default_included BOOLEAN NOT NULL
);

CREATE TABLE checklist_item_products (
    item_id    BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (item_id, product_id)
);

CREATE TABLE checklist_item_housing_types (
    item_id         BIGINT NOT NULL,
    housing_type_id BIGINT NOT NULL,
    PRIMARY KEY (item_id, housing_type_id)
);

CREATE TABLE documents (
    document_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id           BIGINT NOT NULL,
    document_group_id BIGINT,
    document_name     VARCHAR(200) NOT NULL,
    description       TEXT,
    issuer            VARCHAR(200),
    validity_rule     VARCHAR(300),
    submission_form   VARCHAR(100),
    sample_image_url  VARCHAR(1000),
    sort_order        INTEGER NOT NULL
);

CREATE TABLE document_housing_types (
    document_id     BIGINT NOT NULL,
    housing_type_id BIGINT NOT NULL,
    PRIMARY KEY (document_id, housing_type_id)
);

CREATE TABLE document_groups (
    document_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id           BIGINT NOT NULL,
    group_name        VARCHAR(300) NOT NULL,
    sort_order        INTEGER NOT NULL,
    CONSTRAINT uk_document_groups_item_order UNIQUE (item_id, sort_order)
);

CREATE TABLE document_guides (
    document_id           BIGINT PRIMARY KEY,
    preparation_method     TEXT,
    online_availability     VARCHAR(20),
    online_url              VARCHAR(1000),
    offline_availability     VARCHAR(20),
    offline_location         TEXT,
    required_documents       TEXT,
    applicant_eligibility     TEXT,
    fee                       VARCHAR(300),
    processing_time           VARCHAR(300),
    notes                     TEXT[],
    contact_info              VARCHAR(500),
    official_guide_url        VARCHAR(1000),
    hug_reference_urls        TEXT[],
    verified_at               DATE,
    created_at                TIMESTAMPTZ NOT NULL,
    updated_at                TIMESTAMPTZ NOT NULL
);

-- =========================================================
-- 질문 / 선택지
-- =========================================================

CREATE TABLE questions (
    question_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_step  VARCHAR(20) NOT NULL,
    question_order INTEGER NOT NULL,
    question_text  VARCHAR(500) NOT NULL,
    tenant_type    VARCHAR(20),
    landlord_type  VARCHAR(20)
);

CREATE TABLE question_products (
    question_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    PRIMARY KEY (question_id, product_id)
);

CREATE TABLE question_options (
    option_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    option_text VARCHAR(100) NOT NULL
);

CREATE TABLE question_item_effects (
    option_id BIGINT NOT NULL,
    item_id   BIGINT NOT NULL,
    PRIMARY KEY (option_id, item_id)
);

CREATE TABLE question_document_effects (
    option_id   BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    PRIMARY KEY (option_id, document_id)
);

CREATE TABLE question_dependencies (
    parent_option_id  BIGINT NOT NULL,
    child_question_id BIGINT NOT NULL,
    PRIMARY KEY (parent_option_id, child_question_id)
);

-- =========================================================
-- 신청(Application) / 준비서류 진행
-- =========================================================

CREATE TABLE applications (
    application_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    product_id         BIGINT NOT NULL,
    application_status VARCHAR(20) NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL
);

-- application_infos.contract_address는 이후 AES 암호화가 도입되며 TEXT로
-- 넓어졌다(V10). 현재 엔티티가 이미 TEXT를 요구하므로 처음부터 TEXT로 만든다.
CREATE TABLE application_infos (
    application_id               BIGINT PRIMARY KEY,
    housing_type_id              BIGINT,
    contract_address             TEXT,
    contract_type                VARCHAR(20),
    tenant_type                  VARCHAR(20),
    landlord_type                VARCHAR(20),
    fixed_date_confirmed         BOOLEAN,
    officetel_residential_marked BOOLEAN,
    landlord_proxy_contract      BOOLEAN,
    confirmed_at                 TIMESTAMPTZ,
    updated_at                   TIMESTAMPTZ NOT NULL
);

CREATE TABLE checklist_document_results (
    application_id BIGINT NOT NULL,
    document_id    BIGINT NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (application_id, document_id)
);

-- application_document_uploads: validation_status 등 5개 컬럼과 인덱스는
-- V5에서 추가된다(여기서는 최초 업로드 저장에 필요한 원본 컬럼만 만든다).
CREATE TABLE application_document_uploads (
    upload_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    document_id    BIGINT NOT NULL,
    user_file_name VARCHAR(500) NOT NULL,
    storage_key    VARCHAR(1000) NOT NULL,
    mime_type      VARCHAR(100) NOT NULL,
    file_size      BIGINT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL
);

CREATE TABLE document_preparation_checks (
    check_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    document_id    BIGINT NOT NULL,
    checked_at     TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_document_preparation_check_application_document
        UNIQUE (application_id, document_id)
);

-- =========================================================
-- 위험도 진단(Diagnosis)
-- diagnosis_mode/anonymous_access_*는 V8, registry_address_review_confirmed는
-- V12에서 추가된다. user_id/address/deposit/contract_date는 원래 NOT NULL로
-- 시작했다가 V8, V2에서 각각 nullable로 완화된다 - 그 이력을 그대로 재현한다.
-- =========================================================

CREATE TABLE diagnoses (
    analysis_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    address             VARCHAR(500) NOT NULL,
    normalized_address   VARCHAR(500),
    dong_name            VARCHAR(100),
    ho_name              VARCHAR(100),
    housing_type         VARCHAR(30),
    deposit              BIGINT NOT NULL,
    contract_date        DATE NOT NULL,
    contract_area        NUMERIC(12, 2),
    exclusive_area        NUMERIC(12, 2),
    target_floor          INTEGER,
    landlord_name          VARCHAR(100),
    property_snapshot       TEXT,
    status                   VARCHAR(30) NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL,
    updated_at               TIMESTAMPTZ NOT NULL
);

CREATE TABLE diagnosis_results (
    diagnosis_result_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id             BIGINT NOT NULL,
    estimated_sale_price     BIGINT NOT NULL,
    estimated_lease_price     BIGINT NOT NULL,
    risk_score                 INTEGER NOT NULL,
    risk_grade                  VARCHAR(20) NOT NULL,
    valuation_reliability         VARCHAR(20) NOT NULL,
    analyzed_at                    TIMESTAMPTZ NOT NULL,
    response_json                   TEXT NOT NULL,
    created_at                       TIMESTAMPTZ NOT NULL,
    updated_at                       TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_diagnosis_results_analysis_id UNIQUE (analysis_id)
);

-- =========================================================
-- 등기부등본 OCR/파싱 결과
-- registry_results.dong_name/floor/ho_name/exclusive_area는 V13에서 추가되고
-- V14에서 백필된다. source_type CHECK 제약은 V6에서 추가된다.
-- =========================================================

CREATE TABLE registry_results (
    registry_result_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id                     BIGINT NOT NULL,
    parse_status                     VARCHAR(20) NOT NULL,
    parse_confidence                  VARCHAR(10) NOT NULL,
    raw_address                        VARCHAR(255),
    issue_date                          DATE,
    source_type                          VARCHAR(20) NOT NULL,
    raw_text                              TEXT NOT NULL,
    has_cancellation_mention               BOOLEAN NOT NULL,
    gap_section_status                      VARCHAR(20) NOT NULL,
    eul_section_status                       VARCHAR(20) NOT NULL,
    seizure                                   VARCHAR(10) NOT NULL,
    provisional_seizure                        VARCHAR(10) NOT NULL,
    provisional_disposition                     VARCHAR(10) NOT NULL,
    auction_commenced                            VARCHAR(10) NOT NULL,
    trust_registration                            VARCHAR(10) NOT NULL,
    has_active_jeonse_right                        VARCHAR(10) NOT NULL,
    has_active_leasehold_registration               VARCHAR(10) NOT NULL,
    active_mortgage_count                            INTEGER,
    total_active_max_claim_amount                     BIGINT,
    parsed_at                                          TIMESTAMPTZ NOT NULL,
    created_at                                          TIMESTAMPTZ NOT NULL
);

-- registry_owners.share / registry_rights.rank_no,debtor는 V3에서 폭이
-- 넓어진다. 지금 엔티티 폭과 V3의 목표 폭이 이미 같아서(둘 다 이후에 동기화됨)
-- 처음부터 최종 폭으로 만들어도 V3가 같은 타입으로 재적용되어 안전하다.
CREATE TABLE registry_owners (
    registry_owner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registry_result_id BIGINT NOT NULL,
    name                VARCHAR(50) NOT NULL,
    jumin_front          VARCHAR(20) NOT NULL,
    address                VARCHAR(255) NOT NULL,
    share                   VARCHAR(30),
    status                   VARCHAR(20) NOT NULL,
    age                       INTEGER,
    created_at                 TIMESTAMPTZ NOT NULL
);

-- registry_rights.right_type CHECK 제약은 V9에서 추가된다.
CREATE TABLE registry_rights (
    right_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registry_result_id BIGINT NOT NULL,
    section             VARCHAR(10) NOT NULL,
    right_type           VARCHAR(30) NOT NULL,
    rank_no                VARCHAR(20) NOT NULL,
    receipt_no               VARCHAR(30),
    registered_at              DATE,
    holder                       VARCHAR(100),
    debtor                        VARCHAR(100),
    amount                         BIGINT,
    status                          VARCHAR(20) NOT NULL,
    raw_text                         TEXT NOT NULL,
    created_at                        TIMESTAMPTZ NOT NULL
);

CREATE TABLE landlord_watchlist_checks (
    check_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id          BIGINT NOT NULL,
    registry_result_id    BIGINT NOT NULL,
    registry_owner_id       BIGINT,
    check_status              VARCHAR(20) NOT NULL,
    match_status                VARCHAR(20) NOT NULL,
    matched                       BOOLEAN,
    match_type                     VARCHAR(20),
    source                           VARCHAR(50) NOT NULL,
    checked_at                        TIMESTAMPTZ NOT NULL,
    details_json                       TEXT,
    created_at                           TIMESTAMPTZ NOT NULL
);

-- HUG 상습채무불이행자(악성임대인) 명단. 파이썬 크롤러가 주기적으로 통째로 갱신함.
CREATE TABLE bad_landlord (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(50) NOT NULL,
    age                  INTEGER,
    address                VARCHAR(255) NOT NULL,
    address_sigungu         VARCHAR(50),
    return_debt_amount        BIGINT,
    default_days                INTEGER,
    enforcement_count             INTEGER,
    posted_date                    DATE,
    crawled_at                      TIMESTAMPTZ NOT NULL
);

-- =========================================================
-- 챗봇 대화 이력
-- document_chat_histories.session_id는 V15, application_id는 V16에서 추가된다.
-- =========================================================

CREATE TABLE document_chat_histories (
    history_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    document_id BIGINT,
    question    TEXT NOT NULL,
    answer      TEXT NOT NULL,
    sources     TEXT,
    created_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE guide_chat_histories (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    session_id   VARCHAR(64) NOT NULL,
    category      VARCHAR(20) NOT NULL,
    question       TEXT NOT NULL,
    answer          TEXT NOT NULL,
    sources          TEXT,
    created_at        TIMESTAMPTZ NOT NULL
);

-- =========================================================
-- 외래키
-- =========================================================

ALTER TABLE refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE oauth_accounts
    ADD CONSTRAINT fk_oauth_accounts_user FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE checklist_groups
    ADD CONSTRAINT fk_checklist_groups_section FOREIGN KEY (section_id) REFERENCES checklist_sections (section_id);

ALTER TABLE checklist_items
    ADD CONSTRAINT fk_checklist_items_section FOREIGN KEY (section_id) REFERENCES checklist_sections (section_id),
    ADD CONSTRAINT fk_checklist_items_group FOREIGN KEY (group_id) REFERENCES checklist_groups (group_id);

ALTER TABLE checklist_item_products
    ADD CONSTRAINT fk_checklist_item_products_item FOREIGN KEY (item_id) REFERENCES checklist_items (item_id),
    ADD CONSTRAINT fk_checklist_item_products_product FOREIGN KEY (product_id) REFERENCES products (product_id);

ALTER TABLE checklist_item_housing_types
    ADD CONSTRAINT fk_checklist_item_housing_types_item FOREIGN KEY (item_id) REFERENCES checklist_items (item_id),
    ADD CONSTRAINT fk_checklist_item_housing_types_housing_type FOREIGN KEY (housing_type_id) REFERENCES housing_types (housing_type_id);

ALTER TABLE documents
    ADD CONSTRAINT fk_documents_item FOREIGN KEY (item_id) REFERENCES checklist_items (item_id),
    ADD CONSTRAINT fk_documents_document_group FOREIGN KEY (document_group_id) REFERENCES document_groups (document_group_id);

ALTER TABLE document_housing_types
    ADD CONSTRAINT fk_document_housing_types_document FOREIGN KEY (document_id) REFERENCES documents (document_id),
    ADD CONSTRAINT fk_document_housing_types_housing_type FOREIGN KEY (housing_type_id) REFERENCES housing_types (housing_type_id);

ALTER TABLE document_groups
    ADD CONSTRAINT fk_document_groups_item FOREIGN KEY (item_id) REFERENCES checklist_items (item_id);

ALTER TABLE document_guides
    ADD CONSTRAINT fk_document_guides_document FOREIGN KEY (document_id) REFERENCES documents (document_id);

ALTER TABLE question_products
    ADD CONSTRAINT fk_question_products_question FOREIGN KEY (question_id) REFERENCES questions (question_id),
    ADD CONSTRAINT fk_question_products_product FOREIGN KEY (product_id) REFERENCES products (product_id);

ALTER TABLE question_options
    ADD CONSTRAINT fk_question_options_question FOREIGN KEY (question_id) REFERENCES questions (question_id);

ALTER TABLE question_item_effects
    ADD CONSTRAINT fk_question_item_effects_option FOREIGN KEY (option_id) REFERENCES question_options (option_id),
    ADD CONSTRAINT fk_question_item_effects_item FOREIGN KEY (item_id) REFERENCES checklist_items (item_id);

ALTER TABLE question_document_effects
    ADD CONSTRAINT fk_question_document_effects_option FOREIGN KEY (option_id) REFERENCES question_options (option_id),
    ADD CONSTRAINT fk_question_document_effects_document FOREIGN KEY (document_id) REFERENCES documents (document_id);

ALTER TABLE question_dependencies
    ADD CONSTRAINT fk_question_dependencies_parent_option FOREIGN KEY (parent_option_id) REFERENCES question_options (option_id),
    ADD CONSTRAINT fk_question_dependencies_child_question FOREIGN KEY (child_question_id) REFERENCES questions (question_id);

ALTER TABLE applications
    ADD CONSTRAINT fk_applications_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    ADD CONSTRAINT fk_applications_product FOREIGN KEY (product_id) REFERENCES products (product_id);

ALTER TABLE application_infos
    ADD CONSTRAINT fk_application_infos_application FOREIGN KEY (application_id) REFERENCES applications (application_id),
    ADD CONSTRAINT fk_application_infos_housing_type FOREIGN KEY (housing_type_id) REFERENCES housing_types (housing_type_id);

ALTER TABLE checklist_document_results
    ADD CONSTRAINT fk_checklist_document_results_application FOREIGN KEY (application_id) REFERENCES applications (application_id),
    ADD CONSTRAINT fk_checklist_document_results_document FOREIGN KEY (document_id) REFERENCES documents (document_id);

ALTER TABLE application_document_uploads
    ADD CONSTRAINT fk_application_document_uploads_application FOREIGN KEY (application_id) REFERENCES applications (application_id),
    ADD CONSTRAINT fk_application_document_uploads_document FOREIGN KEY (document_id) REFERENCES documents (document_id);

ALTER TABLE document_preparation_checks
    ADD CONSTRAINT fk_document_preparation_checks_application FOREIGN KEY (application_id) REFERENCES applications (application_id),
    ADD CONSTRAINT fk_document_preparation_checks_document FOREIGN KEY (document_id) REFERENCES documents (document_id);

ALTER TABLE diagnoses
    ADD CONSTRAINT fk_diagnoses_user FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE diagnosis_results
    ADD CONSTRAINT fk_diagnosis_results_diagnosis FOREIGN KEY (analysis_id) REFERENCES diagnoses (analysis_id);

ALTER TABLE registry_owners
    ADD CONSTRAINT fk_registry_owners_result FOREIGN KEY (registry_result_id) REFERENCES registry_results (registry_result_id);

ALTER TABLE registry_rights
    ADD CONSTRAINT fk_registry_rights_result FOREIGN KEY (registry_result_id) REFERENCES registry_results (registry_result_id);

ALTER TABLE landlord_watchlist_checks
    ADD CONSTRAINT fk_landlord_watchlist_checks_result FOREIGN KEY (registry_result_id) REFERENCES registry_results (registry_result_id),
    ADD CONSTRAINT fk_landlord_watchlist_checks_owner FOREIGN KEY (registry_owner_id) REFERENCES registry_owners (registry_owner_id);

ALTER TABLE document_chat_histories
    ADD CONSTRAINT fk_document_chat_histories_user FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE guide_chat_histories
    ADD CONSTRAINT fk_guide_chat_histories_user FOREIGN KEY (user_id) REFERENCES users (user_id);

-- =========================================================
-- 인덱스 (엔티티에 명시된 것만)
-- =========================================================

CREATE INDEX idx_diagnoses_user_id ON diagnoses (user_id);
CREATE INDEX idx_bad_landlord_name ON bad_landlord (name);
CREATE INDEX idx_watchlist_checks_analysis_id ON landlord_watchlist_checks (analysis_id);
CREATE INDEX idx_watchlist_checks_result_id ON landlord_watchlist_checks (registry_result_id);
CREATE INDEX idx_registry_owners_result_id ON registry_owners (registry_result_id);
CREATE INDEX idx_registry_owners_name ON registry_owners (name);
CREATE INDEX idx_registry_results_analysis_id ON registry_results (analysis_id);
CREATE INDEX idx_registry_rights_result_id ON registry_rights (registry_result_id);
CREATE INDEX idx_registry_rights_type ON registry_rights (registry_result_id, right_type);
