ALTER TABLE IF EXISTS registry_results
    ADD COLUMN IF NOT EXISTS dong_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS floor INTEGER,
    ADD COLUMN IF NOT EXISTS ho_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS exclusive_area NUMERIC(12, 3);
