spring.application.name=hugme

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# JWT 30분
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=1800000
# Refresh Token: 14일
jwt.refresh-token-expiration=1209600000

# Elasticsearch
spring.elasticsearch.uris=${ELASTICSEARCH_URI}
spring.elasticsearch.username=${ELASTICSEARCH_USERNAME}
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD}

# chatbot
hugme.elasticsearch.document-index=chatbot-documents
hugme.elasticsearch.guide-index=chatbot-guides
hugme.elasticsearch.embedding-dimensions=1536

# ==============================
# Kakao OAuth2 Client
# ==============================

# 카카오 REST API 키
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}

# 카카오 Client Secret
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET}

spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# 받아올 사용자 정보
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,account_email
spring.security.oauth2.client.registration.kakao.client-name=Kakao


# ==============================
# Kakao OAuth2 Provider
# ==============================

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-info-authentication-method=header
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

